Renamed importVarious to post_handler.
The previous code gave an error:

```
...
  File ".../plone/app/caching/setuphandlers.py", line 28, in importVarious
    site = context.getSite()
AttributeError: 'RequestContainer' object has no attribute 'getSite'
```

The code needed more changes when going from import step to post handler.

Since it can no longer be used as import step, anyone using this will need to change their code, so it feels safe to rename the function without leaving a backwards compatibility layer.
The import step was meant for internal use only anyway.